# Welcome to LootCrate! An awesome fun mechanic inspired by a popular first person shooter.
# Everything is carefully explained as some configurations are a bit tricky to do properly. If you need support or
# assistance setting up your configuration, feel free to post a reply or send me (ArjanforGames) a private message.

# Put true here to reset the config to its default settings.
## Usage: true/false
ResetConfig: false

# Do you want LootCrate to be enabled?
## Usage: true/false
Enabled: true

# Loot is seperated into different tiers. Put the amount of tiers you want to have below.
## Usage: 1/2/3...
Tiers: 3

# All tiers have different colors so you can identify them a bit easier. For every tier you want, pick a color.
# NOTE: These are colors for the panes, NOT chat colors!
# Available colors are: WHITE, ORANGE, MAGENTA, LIGHT_BLUE, YELLOW, LIME, PINK, GRAY, LIGHT_GRAY, CYAN, PURPLE, BLUE,
# BROWN, GREEN, RED and BLACK.
## For the usage, see the default example(s) below. This should be exactly the same for every tier you have.
TierColor:
    1: "RED"
    2: "GREEN"
    3: "BLUE"

# The amount of different crates you wish to create needs to be specified below.
## Usage: 1/2/3...
Crates: 2

# The biggest part of this plugin is to feature lootchests ofcourse! You can add as many lootchest types as you like.
# The chance is the chance in percentage for a tier to spawn in a slot. In the example below, tier one has a 75 percent
# chance to spawn and tier two a 25 percent chance. 
# NOTE: You don't need to add up to 100 percent. If you use the same values that simply means it's a fifty-fifty chance.
# NOTE 2: Do NOT use tiers that are not configured earlier or the plugin will throw an error.
# NOTE 3: You can also add colors to the names by using a percentage sign (%) and then a color code. (http://minecraft.gamepedia.com/Formatting_codes)
## For the usage, see the default example(s) below. This should be exactly the same for every chest you have.
CrateInfo:
    Crate1:
        Name: "%fMister Default"
        Tiers: [1,2]
        Chances: [100,100]
    Crate2:
        Name: "%6Awesome Crate"
        Tiers: [3]
        Chances: [100]

# Now that we have all tiers and chests set up, we're going to move on to the part where we decide what items are rewarded.
# For a list of accurate item ID's, visit http://minecraft-ids.grahamedgecombe.com/
# The quantity is used to tell the plugin how many of a specific item should be awarded.
# In this example we have (In tier1): Glass, Sticky Piston, Gold Block, Furnace, Anvil, Iron Sword, Golden Shovel and a Diamond Chestplate.
# In this example we have (In tier2): Pumpkin, Jack o'Lantern, Vines, Enchantment Table, Cauldron, Beacon, Barrier and a Flint and Steel.
# NOTE: Data values are not supported yet!
## For the usage, see the default example(s) below. This should be exactly the same for every chest you have.
CrateContents:
    Crate1:
        Tier1:
            Items: [20,29,41,61,145,267,284,311]
            Chance: [100,100,100,100,100,100,100,100]
            Quantity: [10,2,1,2,1,1,1,1]
        Tier2:
            Items: [86,91,106,116,118,138,166,259]
            Chance: [100,100,100,100,100,100,100,100]
            Quantity: [10,5,64,1,1,1,5,1]
    Crate2:
        Tier3:
            Items: [20,29,41,61,145,267,284,311]
            Chance: [100,100,100,100,100,100,100,100]
            Quantity: [10,2,1,2,1,1,1,1]

# Now that our crates are configured, we want to configure how fast the crates will switch slots 'or spin'.
# The speed is configured in ticks. 20 ticks is one second.
# The higher the amount of ticks you put in here, the longer it will take for the items to switch slots.
## Usage: Amount of ticks
SpeedFirstStage: 5
SpeedSecondStage: 10
SpeedThirdStage: 20

# The default item that appears at the end of the uncrate are the iron bars that move towards the middle.
# If you don't like the iron bars you can pick any item you desire by putting the item ID down here.
## Usage: Item ID (http://minecraft-ids.grahamedgecombe.com/)
FinalStage: 101
# You can also change the speed in which they appear.
## Usage: Amount of ticks
SpeedFinalStage: 20

# Sounds are always nice to have and just makes everything a little better.
# NOTE: As there are too many sounds to list in here, please visit https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
# This is the sound that is being played while the lootcrate is 'spinning'
## Usage: Sound name
SpinningSound: "CHICKEN_EGG_POP"

# You can change the sound of the items closing in to the middle and the final sound that gets played when
# the two final closing items have appeared.
## Usage: Sound name
FinalStageSound: "ANVIL_LAND"
FinalStageSucces: "LEVEL_UP"

# Signs. Players can uncrate using a sign if the sign is set up properly and if the player has the right permission.
# At this moment signs can not be disabled, because if you do not want them, you simply remove them ;)
# If you want the player to pay a specific amount of the currency you are using, then you can set it up below.
# Do you want LootCrate to set up a hook with Vault?
## Usage: true/false
UseVault: false
# And what should the price be?
UncratePrice: 0